jobs:
  install_php:
    docker:
      - image: 'cimg/base:edge'
    steps:
      - checkout
      - php/install-php:
          version: '7.3'
orbs:
  php: circleci/php@1.1.0
version: 2.1
workflows:
  install:
    jobs:
      - install_php