version: 2.1
jobs:
  build:
    docker:
      - image: cimg/php:8.1
    environment:
      CC_TEST_REPORTER_ID: 7b1ac919c90c8ea384b4998b267e0f629185a26ffdf0f96ef4f4a09f53488ed2
      XDEBUG_MODE: coverage
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Set up Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: Run tests
          command: |
            composer install
            ./cc-test-reporter before-build
            ./vendor/bin/phpunit --testsuite all --coverage-clover clover.xml
            sed -i 's+/var/www/html/+/home/circleci/repo/+g' clover.xml
            ./cc-test-reporter after-build --coverage-input-type clover --exit-code $?
